## My introduction to using GitHub
### Anna Moeller
### 9 November 2017

There are a few things you need to know to get started.
1. Git is different than GitHub. Git is a version control system. GitHub uses Git in the background. 
2. You have two options for making local changes on your computer offline. They are Git (which is command line-based) and GitHub Desktop (which is software with a GUI). 
    - I use GitHub Desktop, which is handy and makes sense for most things. However, you can't do everything in it, so you still have to use your online GitHub. 
    
Now go set up an [online GitHub account](https://github.com/) and download the latest version of [GitHub Desktop](https://desktop.github.com/)

Using GitHub for your personal benefit is slightly different than for collaborating with others. Almost all the documentation is about collaborating with others, so let's break the mold and start with how to create your own repository for yourself. 

### Using GitHub for your own work
When you're the person in charge of the project, you want to use "clone"

Online:
1. Create a repository (this creates it online)

GitHub Desktop:

1. Clone your repository (This should put a folder on your computer in ~/GitHub/repo name)
2. Use that folder like you would with any other folder. Add code, make changes, etc.
3. Every time you make a change, open GitHub Desktop and commit it. This commits it to your computer's log. 
4. Sync (this takes it from your computer to online)
 
Voila!


### Using GitHub to collaborate
When you're *not* the person in charge of the project, you want to use "fork" instead of "clone"

In your GitHub online: 
1. navigate to the [RGroup repository](github.com/annam21/RGroup). 
2. Fork this repository. This creates a fork from annam21/RGroup to your profile called yourusername/RGroup.

GitHub Desktop:
1. Clone yourusername/RGroup repository. 
2. Manipulate files, code, etc. and make commits to your local Desktop. 
3. When you are ready to send me your changes, create a pull request (i.e., ask me to "pull" your changes into my repository). This will ask me to accept your changes from your fork yourusername/RGroup to my repository annam21/RGroup
4. I will get an email about your pull request. I can go into my online GitHub repo and merge your pull request, which adds all your changes to the master repo. 

